kind: pipeline
name: default

services:
- name: db
  image: mariadb:10.7.3
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test


steps:
- name: supla-server-test
  image: devel/supla-core
  pull: never
  depends_on: [db]
  commands:
    #    - sleep 10
    - test/supla-server-test.sh
  environment:
    DBHOST: db

- name: supla-console-client-test
  image: devel/supla-core
  pull: never
  depends_on: [supla-server-test]
  when:
    status: [success, failure]
  commands:
    #    - sleep 10
    - test/supla-console-client-test.sh
  environment:
    DBHOST: db

- name: supla-scheduler-test
  image: devel/supla-core
  pull: never
  commands:
    - ./test/supla-scheduler-test.sh

- name: supla-dev-compilation-check
  image: devel/supla-core
  pull: never
  commands:
    - ./test/supla-dev-compilation-check.sh

- name: supla-server-compilation-check
  image: devel/supla-core
  pull: never
  commands:
    - ./test/supla-server-compilation-check.sh

- name: supla-scheduler-compilation-check
  image: devel/supla-core
  pull: never
  commands:
    - ./test/supla-scheduler-compilation-check.sh

- name: supla-console-client-compilation-check
  image: devel/supla-core
  pull: never
  commands:
    - ./test/supla-console-client-compilation-check.sh


- name: cpplint
  image: devel/supla-core
  pull: never
  commands:
    - ./tools/lint.sh

- name: joining
  image: devel/supla-core
  pull: never
  depends_on: [supla-server-test, supla-scheduler-test, supla-console-client-test, supla-dev-compilation-check, supla-server-compilation-check, supla-scheduler-compilation-check, supla-console-client-compilation-check, cpplint]
  commands:
    - echo "test"
      
    #- name: test
    # image: mariadb
  #  commands:
  # - ./supladevicetests --gtest_repeat=50 --gtest_shuffle

- name: rocket
  image: mike1pol/drone-rocket
  depends_on: [joining]
  settings:
    url: { from_secret: rocket_url }
    user_id: { from_secret: rocket_user }
    token: { from_secret: rocket_token }
    channel: github
    avatar_url: "https://miro.medium.com/max/256/0*AqO_2lNemh_Fl9Gm.png"
  when:
    status: [success, failure]
    event:
      exclude:
        - pull_request

